### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/love-running#1]
In order to organize a run that hasn't been scheduled as a community member, I can do so by having the ability to do it on the website.

**Comment by IzzyLeech** [comment]
## Acceptance Criteria:

- Have a section for members of the community to be able to post in
- Create a post so that members can scheduled runs

**Comment by IzzyLeech** [comment]
## Tasks:

- [ ] Create a section where the community can interact with each other.
- [ ] Create the ability for the members to create posts in the section.
- [ ] Create the ability in the post for the members to reply to each other in the post.
