### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/love-running#2]
In order to see how many members are participating in a run as an administrator, I can tally the number of people who are interested in the run with a tally.

**Comment by IzzyLeech** [comment]
## Acceptance Criteria:

- Have a section where the community can interact.
- Have an administrator be able to post in the forum for upcoming runs asking for a thumbs-up emoji it they are showing up.

**Comment by IzzyLeech** [comment]
## Task:

- [ ] Create an area for the community to be able to post.
- [ ] Create an option so that administrator can with administrator privilege.
- [ ] Create an input field for a description
- [ ] Create an option for emoji for thumbs up and thumbs down.
- [ ] Create a visual for the number of submits.
